
{{ if hasKey .Values.env }}
  {{ fail "The Value env has been renamed and moved to dastyar.configEnv. Refer to https://www.dastyar.ai/docs/local/helm_chart#migrate for more information" }}
{{ end }}